### ISSUE TITLE
Crimes - Do not hard-code capture date

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-community-profiles#14]
Because we will be using the most recent full year, change the hard-coded 2016 to a variable

**Comment by SPTKL** [comment]
I'm thinking all the versioning should be included in the `version.env`
e.g. for pluto, facdb, and ACS
https://github.com/NYCPlanning/db-community-profiles/blob/master/cdprofiles_build/version.env

**Comment by SPTKL** [comment]
e006099
