### ISSUE TITLE
Create different data tables for download

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-community-profiles#33]
Grouping the existing data, new field names, and new order
[CDProfiles-indicators-groupings-UPDATE.xlsx](https://github.com/NYCPlanning/db-community-profiles/files/5247415/CDProfiles-indicators-groupings-UPDATE.xlsx)

**Comment by mgraber** [comment]
Create an export sql script to creates two views of the big table powering the app. This will also map the app field names to the ones requested for download.

**Comment by AmandaDoyle** [comment]
Add 
son_issue_1
son_issue_2
son_issue_3
TO CD admin table

**Comment by jorgeh01** [comment]
@AmandaDoyle Everything looks good, thanks for making the updates.
