### ISSUE TITLE
Source:  Parks

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-community-profiles#7]
# Schema
Field Name | Description | Source
-- | -- | --
pct_served_parks | The percentage of residents of the CD within walking distance of a park or open space. Walking distance is defined as 1/4 mile for parks less than 6 acres, and 1/2 mile for larger parks and pools. | NYC Department of Parks and Recreation, 2016

# Process
Unknown

# Resource
Unknown

**Comment by AmandaDoyle** [comment]
Potential workflow
Take parks catchment area from open data and we'll compute percent of population served

**Comment by AmandaDoyle** [comment]
@cfpolack @jorgeh01 
Do we agree that we can use [this dataset](https://data.cityofnewyork.us/Recreation/Walk-to-a-Park-Service-area/5vb5-y6cv) to determine the percentage of a CD that is within walking distance to a park?

**Comment by cfpolack** [comment]
@AmandaDoyle We will need to confirm this with Parks before proceeding -- we will work on reaching out to our contact at Parks and will follow-up with you when we have an answer on this.

**Comment by AmandaDoyle** [comment]
@cfpolack Okay.  Please feel free to cc me on any emails.

**Comment by jorgeh01** [comment]
@AmandaDoyle Email sent to Antonios Michelakis at Parks. Sorry for the delay!

**Comment by mgraber** [comment]
Methodology as recommended by Parks: weight 2010 decennial census block level population by the proportion of the block area that is within the parks walking distance boundary. Aggregate these by cd.
