### ISSUE TITLE
'city_cd_attributes' has 7 rows when it should have 1.  moe_over65 is not the same

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-community-profiles#75]
'city_cd_attributes' has 7 rows when it should have 1.  moe_over65 is not the same

**Comment by SPTKL** [comment]
can you provide more detail, and the exact record / sql query

**Comment by AmandaDoyle** [comment]
`city_cd_attributes` is the csv file that reports attributes at the citywide level.  I haven't dug into any code yet.
