### ISSUE TITLE
out_cd_geo.sql needs to used clipped to shoreline CD boundaries

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-community-profiles#76]
out_cd_geo.sql needs to used clipped to shoreline CD boundaries
The area of the CDs are much larger compared to previous version.  Calculation is correct.  Values align on land locked CDs

**Comment by SPTKL** [comment]
create new table in recipes 
dcp_cdboundaries_wi -> water included and change the table name involved in calculation
https://github.com/NYCPlanning/db-community-profiles/blob/a9b4a7a3fe649484f66212a61a12b39df6fcf7f2/cdprofiles_build/sql/out_cd_geo.sql#L7

**Comment by mgraber** [comment]
Currently in recipes, the schema `dcp_cdboundaries` is a water-included version. Need to rename to `dcp_cdboundaries_wi` and create a new schema of shoreline-clipped called `dcp_cdboundaries`.
