### ISSUE TITLE
Source: DCP

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-community-profiles#8]
# Schema

Field Name | Description
-- | --
cd_son_fy2018 | URL for CD's Statement of Community District Needs and Community Board Budget Requests for Fiscal Year 2018
son_issue_1 | Most pressing issue identified by the community board in the Statement of Community District Needs and Community Board Budget Requests for Fiscal Year 2018
son_issue_2 | Second most pressing issue identified by the community board in the Statement of Community District Needs and Community Board Budget Requests for Fiscal Year 2018
son_issue_3 | Third most pressing issue identified by the community board in the Statement of Community District Needs and Community Board Budget Requests for Fiscal Year 2018
neighborhoods | Neighborhoods that are partially or completely within the CD. Neighborhood names and boundaries are not officially designated.

# Process

# Resource

**Comment by cfpolack** [comment]
Talk to Labs about:
- Renaming 'cd_son_fy2018' to 'cd_son_link'
- Removing year reference from description for 'son_issue_1', 'son_issue_2', 'son_issue_3'

**Comment by AmandaDoyle** [comment]
@cfpolack  @jorgeh01  Do you have a standard source that we can pull these values from?  If not, will you then update a csv with these values each year?

**Comment by cfpolack** [comment]
@AmandaDoyle We do not have a standard source for these values -- we will need to update a csv with those values each year.

**Comment by AmandaDoyle** [comment]
Flagging for @mgraber ^

**Comment by AmandaDoyle** [comment]
@cfpolack  can you provide a csv with the SONs that we can build off of?

**Comment by mgraber** [comment]
We will be building an initial SON cvs by extracting the relevant columns from the current community profiles table. This will then get updated via github.
