### ISSUE TITLE
Questions from PC

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-community-profiles#80]
1. Should this current output include the standardized percentages? I see some percentages that are on a 0-100 scale while others are 0-1
> Our output is currently matching what is expected by the app. Do we fix on our end first?

2. It looks like some 0 values are saved as 0 in the output while other cells are blank, for example in the cd_floodplain.csv file some values are zeroes while others are empty
> There are lots of ways that demographic data can be either 0 or missing. The floodplain case is especially complicated. For example, consider the basic statistic of the number of people within the floodplain. There could either be area that is floodplain, but no one lives in that area (0), or there could be no area in the floodplain to begin with (NULL). Many of the other statistics derive from population, since the app presents rates. For rates, there is a difference between 0% of a non-zero population having some characteristic (displayed as a 0) and a rate not making sense because the population within the floodplain is 0 to begin with, for either of the two reasons described above (NULL). In short: zero means zero, while NULL means "this statistic doesn't make sense for this area"

> The current table is confusing, though, because it mixes decennial population data with acs data. So fp_500_pop and fp_100_pop are not the denominators for rates. Instead, denominators are whatever the associated base variable is in the ACS data. Since the decennial floodplain aggregations roll up blocks, while the ACS floodplain aggregations roll up block groups, the ACS population might be capturing people who live in blocks that are outside the floodplain, but within the same block group as a different block that's inside the floodplain.

3. We now have the newest statement of needs issues (2020 submissions) for the cd_administrative.csv file -- can we provide these to you to include in the next run of this output? Additionally, I noticed some strange characters in some of the text here, for example "Youth and children¬ís services"
Given that this is a separate data source, should we include a new entry in the "versions.csv" file to specify the current year for the statement of needs issues? 
> The weird characters are coming directly from the [csv](https://github.com/NYCPlanning/db-community-profiles/blob/master/cdprofiles_build/data/cd_son.csv), which contains the statement of needs data as contained in the app's download. To fix we would need to fix the csv.

4. In the past the "pct_served_parks" (in cd_built_environment file) has been rounded to the nearest percent, but in the current output it appears that the numbers are being rounded to the nearest 10%
> We can fix this

**Comment by cfpolack** [comment]
@AmandaDoyle Thank you for the quick replies! A few follow-ups:

2. I also encountered the 0/null difference in the [boro_cd_attrivutes.csv](https://github.com/NYCPlanning/db-community-profiles/blob/master/cdprofiles_build/output/boro_cd_attributes.csv) file -- here, some of the boroughs had a nonzero moe for under18 while others were blank

3. I'll work on this new file today -- should we send via teams or create a pull request?
